#!/bin/bash
#
# File:    xpm_convert.sh
#
# Author:  Schuyler Martin <sam8050@rit.edu>
#
# Description: Uses the ImageMagick toolkit to converts a given image to an XPM
#              file that has been shrunk
#

USAGE="./xpm_convert.sh file"
# quantization factor; how many colors should be in the image
COLOR_QUANT=16
# color space quantization is done in
COLOR_QUANT_SPACE="YCbCr"
# size parameters for the image
SIZE="80x50"

if [[ -z $1 ]]; then
    >&2 echo ${USAGE}
    exit 1
fi

# rename the output file
fd_in="$1"
fd_out="${fd_in%.*}".xpm
# rework the output path
fd_out=$(echo "${fd_out}" | sed 's/img_original/img_xpm/g')

# run conversion
convert "${fd_in}" \
    -quantize ${COLOR_QUANT_SPACE} \
    +dither \
    -resize ${SIZE} \
    -colors ${COLOR_QUANT} \
    "${fd_out}"

# check for errors
if [ $? -eq 0 ]; then
    echo "Image processed..."
else
    >&2 echo "Error in image conversion"
    exit 2
fi

# slight modifications to the file, remove all comments
sed -i '/\/\*.*\*\//,+0 d' "${fd_out}"
# add a leading comment to the top of the file
header_comment="/* XPM $(basename ${fd_out}) generated by xpm_convert.sh */"
sed -i "1i${header_comment}" "${fd_out}"

echo "Image written to ${fd_out}"
